# Generated by Django 3.2.20 on 2024-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='placed_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(verbose_name='50')),
                ('batch', models.TextField(max_length='50')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.TextField(max_length=30)),
                ('phone', models.TextField(max_length=15)),
                ('email', models.TextField(max_length=50)),
                ('linkedin', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(max_length=30)),
                ('enrlno', models.TextField(max_length=20)),
                ('image', models.ImageField(upload_to='upload/')),
                ('name', models.TextField(max_length=30)),
                ('phone', models.TextField(max_length=15)),
                ('email', models.TextField(max_length=50)),
                ('linkedin', models.TextField(max_length=100)),
                ('skills', models.TextField(max_length=500)),
            ],
        ),
    ]
