# Generated by Django 3.2.20 on 2024-01-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
