# Generated by Django 3.2.20 on 2024-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
    ]
