# Generated by Django 3.2.20 on 2024-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.TextField(default='DefaultRollNo', max_length=30),
        ),
    ]
