# Generated by Django 3.2.20 on 2024-02-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_student_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='placed_students',
            name='phone',
        ),
    ]
