# Generated by Django 3.2.20 on 2024-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20240201_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(default='MCA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrlno',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.TextField(default='22CAMSA420', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
