# Generated by Django 3.2.20 on 2024-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20240201_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.TextField(max_length=30),
        ),
    ]
