# Generated by Django 3.2.20 on 2024-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desc',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
