# Generated by Django 3.2.20 on 2024-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_student_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='insta',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
