# Generated by Django 3.2.20 on 2024-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_auto_20240213_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='media/upload'),
        ),
    ]
