# Generated by Django 3.2.20 on 2024-02-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
