# Generated by Django 3.2.20 on 2024-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_alter_student_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
