# Generated by Django 3.2.20 on 2024-03-02 22:57

import APP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=APP.models.filepath),
        ),
    ]
